Indtast27Mål/Indtast27Mål/Models/EgeMål.cs
using System;
using System.Collections.Generic;

// Code scaffolded by EF Core assumes nullable reference types (NRTs) are not used or disabled.
// If you have enabled NRTs for your project, then un-comment the following line:
// #nullable disable

namespace Indtast27Mål.Models
{
    public partial class EgeMål
    {
        public int Id { get; set; }
        public string? Kategori { get; set; }
        public string? StatusEgedal { get; set; }
        public string? StatusDanmark { get; set; }
        public string? SenesteEgedal { get; set; }
        public string? SenesteDanmark { get; set; }
        public string? Placering { get; set; }
        public string? Hvad { get; set; }
        public string? Hvorfor { get; set; }
        public string? Initiativer { get; set; }
        public string? Indikator { get; set; }
        public string? Dato { get; set; }

    }
}

Indtast27Mål/Indtast27Mål/Models/ErrorViewModel.cs
using System;

namespace Indtast27Mål.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Indtast27Mål/Indtast27Mål/Controllers/EgeMålController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Indtast27Mål.Data;
using Indtast27Mål.Models;

namespace Indtast27Mål.Controllers
{
    public class EgeMålController : Controller
    {
        private readonly MålDbContext _context;

        public EgeMålController(MålDbContext context)
        {
            _context = context;
        }

        // GET: EgeMål
        public async Task<IActionResult> Index()
        {
            return View(await _context.EgeMål.ToListAsync());
        }

        // GET: EgeMål/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var egeMål = await _context.EgeMål
                .FirstOrDefaultAsync(m => m.Id == id);
            if (egeMål == null)
            {
                return NotFound();
            }

            return View(egeMål);
        }

        // GET: EgeMål/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: EgeMål/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Kategori,StatusEgedal,StatusDanmark,SenesteEgedal,SenesteDanmark,Placering,Hvad,Hvorfor,Initiativer")] EgeMål egeMål)
        {
            if (ModelState.IsValid)
            {
                _context.Add(egeMål);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(egeMål);
        }

        // GET: EgeMål/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var egeMål = await _context.EgeMål.FindAsync(id);
            if (egeMål == null)
            {
                return NotFound();
            }
            return View(egeMål);
        }

        // POST: EgeMål/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Kategori,StatusEgedal,StatusDanmark,SenesteEgedal,SenesteDanmark,Placering,Hvad,Hvorfor,Initiativer,Indikator, Dato")] EgeMål egeMål)
        {
            if (id != egeMål.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(egeMål);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EgeMålExists(egeMål.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(egeMål);
        }

        // GET: EgeMål/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var egeMål = await _context.EgeMål
                .FirstOrDefaultAsync(m => m.Id == id);
            if (egeMål == null)
            {
                return NotFound();
            }

            return View(egeMål);
        }

        // POST: EgeMål/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var egeMål = await _context.EgeMål.FindAsync(id);
            _context.EgeMål.Remove(egeMål);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EgeMålExists(int id)
        {
            return _context.EgeMål.Any(e => e.Id == id);
        }
    }
}

Indtast27Mål/Indtast27Mål/Controllers/HomeController.cs
using Indtast27Mål.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Indtast27Mål.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Indtast27Mål/Indtast27Mål/Views/EgeMål/Create.cshtml
@model Indtast27Mål.Models.EgeMål

@{
    ViewData["Title"] = "Create";
}





<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Kategori" class="control-label"></label>
                <input asp-for="Kategori" class="form-control" />
                <span asp-validation-for="Kategori" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StatusEgedal" class="control-label"></label>
                <input asp-for="StatusEgedal" class="form-control" />
                <span asp-validation-for="StatusEgedal" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StatusDanmark" class="control-label"></label>
                <input asp-for="StatusDanmark" class="form-control" />
                <span asp-validation-for="StatusDanmark" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SenesteEgedal" class="control-label"></label>
                <input asp-for="SenesteEgedal" class="form-control" />
                <span asp-validation-for="SenesteEgedal" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SenesteDanmark" class="control-label"></label>
                <input asp-for="SenesteDanmark" class="form-control" />
                <span asp-validation-for="SenesteDanmark" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Placering" class="control-label"></label>
                <input asp-for="Placering" class="form-control" />
                <span asp-validation-for="Placering" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Hvad" class="control-label"></label>
                <input asp-for="Hvad" class="form-control" />
                <span asp-validation-for="Hvad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Hvorfor" class="control-label"></label>
                <input asp-for="Hvorfor" class="form-control" />
                <span asp-validation-for="Hvorfor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Initiativer" class="control-label"></label>
                <input asp-for="Initiativer" class="form-control" />
                <span asp-validation-for="Initiativer" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Indikator" class="control-label"></label>
                <input asp-for="Indikator" class="form-control" />
                <span asp-validation-for="Indikator" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Dato" class="control-label"></label>
                <input asp-for="Dato" class="form-control" />
                <span asp-validation-for="Dato" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Indtast27Mål/Indtast27Mål/Views/EgeMål/Delete.cshtml
@model Indtast27Mål.Models.EgeMål

@{
    ViewData["Title"] = "Delete";
}

<h1></h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4></h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Kategori)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Kategori)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.StatusEgedal)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.StatusEgedal)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.StatusDanmark)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.StatusDanmark)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.SenesteEgedal)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.SenesteEgedal)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.SenesteDanmark)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.SenesteDanmark)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Placering)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Placering)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Hvad)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Hvad)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Hvorfor)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Hvorfor)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Initiativer)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Initiativer)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Indikator)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Indikator)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Dato)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Dato)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Indtast27Mål/Indtast27Mål/Views/EgeMål/Details.cshtml
@model Indtast27Mål.Models.EgeMål

@{
    ViewData["Title"] = "Details";
}

<h1></h1>

<div>
    <h4></h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Kategori)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Kategori)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.StatusEgedal)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.StatusEgedal)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.StatusDanmark)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.StatusDanmark)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.SenesteEgedal)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.SenesteEgedal)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.SenesteDanmark)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.SenesteDanmark)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Placering)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Placering)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Hvad)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Hvad)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Hvorfor)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Hvorfor)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Initiativer)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Initiativer)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Indikator)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Indikator)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Dato)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Dato)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Indtast27Mål/Indtast27Mål/Views/EgeMål/Edit.cshtml
@model Indtast27Mål.Models.EgeMål

@{
    ViewData["Title"] = "Edit";
}

<h1></h1>

<h4></h4>
<hr />
<div class="row" >
    <div class="col-md-4">
        <form asp-action="Edit" >
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Kategori" class="control-label"></label>
                <input asp-for="Kategori" class="form-control" />
                <span asp-validation-for="Kategori" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StatusEgedal" class="control-label"></label>
                <input asp-for="StatusEgedal" class="form-control" />
                <span asp-validation-for="StatusEgedal" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StatusDanmark" class="control-label"></label>
                <input asp-for="StatusDanmark" class="form-control" />
                <span asp-validation-for="StatusDanmark" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label @*asp-for="SenesteEgedal"*@ class="control-label">SenestePlaceringEgedal</label>
                <input asp-for="SenesteEgedal" class="form-control" />
                <span asp-validation-for="SenesteEgedal" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SenesteDanmark" class="control-label"></label>
                <input asp-for="SenesteDanmark" class="form-control" />
                <span asp-validation-for="SenesteDanmark" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Placering" class="control-label"></label>
                <input asp-for="Placering" class="form-control" />
                <span asp-validation-for="Placering" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Hvad" class="control-label"></label>
                <input asp-for="Hvad" class="form-control" />
                <span asp-validation-for="Hvad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Hvorfor" class="control-label"></label>
                <input asp-for="Hvorfor" class="form-control" />
                <span asp-validation-for="Hvorfor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Initiativer" class="control-label"></label>
                <input asp-for="Initiativer" class="form-control" />
                <span asp-validation-for="Initiativer" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Indikator" class="control-label"></label>
                <input asp-for="Indikator" class="form-control" />
                <span asp-validation-for="Indikator" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Dato" class="control-label"></label>
                <input asp-for="Dato" class="form-control" />
                <span asp-validation-for="Dato" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Indtast27Mål/Indtast27Mål/Views/EgeMål/Index.cshtml
@model IEnumerable<Indtast27Mål.Models.EgeMål>

@{
    ViewData["Title"] = "";
}

<p>
    <a asp-action="Create">Create</a>
</p>
<div style="left: 200px;">
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Kategori)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.StatusEgedal)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.StatusDanmark)
                </th>
                <th>
                    SenestPlaceringEgedal@*@Html.DisplayNameFor(model => model.SenesteEgedal)*@
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.SenesteDanmark)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Placering)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Hvad)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Hvorfor)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Initiativer)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Indikator)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Dato)
                </th>
            </tr>
        </thead>
        <tbody style="left: 50px;">
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Kategori)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.StatusEgedal)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.StatusDanmark)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.SenesteEgedal)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.SenesteDanmark)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Placering)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Hvad)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Hvorfor)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Initiativer)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Indikator)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Dato)
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                        <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                        <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>

</div>

Indtast27Mål/Indtast27Mål/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Indtast27Mål/Indtast27Mål/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <img src="~/images/egedal1.png" style="right: 400px;" />
                <a class="navbar-brand" asp-area="" asp-controller="EgeMål" asp-action="Edit"></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index"></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy"></a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Egedal kommune - <a asp-area="" asp-controller="Home" asp-action="Privacy"></a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>